# inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  RubyInterpreters:
    - ruby
  Exclude:
    - '**/*.gemspec'
    - 'test/**/*.rb'
    - 'examples/**/*.rb'
    - 'Gemfile'

# Style/ModuleFunction:
  # Enabled: false
Style/RegexpLiteral:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Layout/AlignHash:
  EnforcedColonStyle: table

Security/Eval:
  Exclude:
    - 'lib/modulation/modules/bootstrap.rb'

Metrics/ModuleLength:
  Max: 110 # default is 100