# inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  RubyInterpreters:
    - ruby
  Exclude:
    - '**/*.gemspec'
    - 'test/**/*.rb'
    - 'examples/app/package.rb'
    - 'Gemfile'

# Style/ModuleFunction:
  # Enabled: false
Style/RegexpLiteral:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Layout/AlignHash:
  EnforcedColonStyle: table

Security/Eval:
  Exclude:
    - 'lib/modulation/modules/bootstrap.rb'

Metrics/ModuleLength:
  Max: 110 # default is 100

Lint/NestedMethodDefinition:
  Exclude:
    - 'test/test_modulation.rb'

Metrics/MethodLength:
  Exclude:
    - 'test/**/*.rb'
    - 'examples/**/*.rb'

Metrics/AbcSize:
  Exclude:
    - 'test/**/*.rb'
    - 'examples/**/*.rb'

Style/LambdaCall:
  EnforcedStyle: braces

Style/DoubleNegation:
  Enabled: false

Style/MissingRespondToMissing:
  Exclude:
    - 'examples/**/*.rb'

Style/MethodMissingSuper:
  Exclude:
    - 'examples/**/*.rb'

Naming/UncommunicativeMethodParamName:
  Exclude:
    - 'examples/**/*.rb'

Style/FrozenStringLiteralComment:
  Exclude:
  - 'examples/**/*.rb'
