name: Modulation Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Repo checkout
      uses: actions/checkout@v2

    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - name: RubyGems, Bundler Update
      run:  gem update --system --no-document --conservative

    - name: bundle install
      run:  bundle install --path .bundle/gems --without development

    - name: test
      run:  bundle exec rake test
      timeout-minutes: 10
